baseURL = "https://dosedaf.github.io/dosedaf-web/"
languageCode = "en-us"
theme = "nostyleplease"

[params]
author = "dosedaf"
description = "we on it"

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Writings"
url = "/dosedaf-web/writings/"
weight = 2
[[menu.main]]
name = "Projects"
url = "/dosedaf-web/projects/"
weight = 3
